name: Build and run unit tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip3 install -e '.[test]'
      - name: Test
        run: python3 -m pytest -v --cov=ace tests

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install flake8
        run: pip3 install -e '.[flake8]'
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "flake8"
          path: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
